### ISSUE TITLE
"gradle clean" doesn't work...

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-master#2]
when the target "gradle cTGM" has bee executed, 
the standard "gradle clean" is no longer available:

    gradle clean
    FAILURE: Build failed with an exception.
    * Where:
    Build file '/Users/gstarke/projects/arc42/arc42-template/build.gradle' line: 46
    * What went wrong:
    A problem occurred evaluating root project 'arc42-template'.
    > Declaring custom 'build' task when using the standard Gradle lifecycle plugins is not allowed.
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    BUILD FAILED

**Comment by rdmueller** [comment]
the cTFGM task creates new build files which include an empty build task. That's ok for old gradle versions (even needed for some features) but newer version run into the failure mentioned above.

Please use the gradle-wrapper (gradlew) provided by the project.
